name: Android Build and Lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew build test

      - name: Lint with ktlint
        run: ./gradlew ktlintCheck

      - name: Analyze with detekt
        run: ./gradlew detekt
